services:
  nats:
    image: nats:2.10-alpine
    container_name: nexus-nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command:
      ["--js", "--sd", "/data", "--http_port", "8222", "--name", "nexus-nats"]
    volumes:
      - nats_data:/data
    networks:
      - nexus-network

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: nexus-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: nexus_users
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - nexus-network
    command: mongod --auth

  mongo-express:
    image: mongo-express:1.0.2
    container_name: nexus-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - nexus-network

  nexus-gateway:
    build:
      context: ./ms-nexus-gateway
      dockerfile: Dockerfile.dev
      target: development
    container_name: nexus-gateway
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - NATS_SERVERS=nats://nats:4222
      - PORT=8000
    volumes:
      # Montar c贸digo fuente para hot reload
      - ./ms-nexus-gateway/src:/app/src:cached
      - ./ms-nexus-gateway/package.json:/app/package.json:cached
      - ./ms-nexus-gateway/tsconfig.json:/app/tsconfig.json:cached
      - ./ms-nexus-gateway/nest-cli.json:/app/nest-cli.json:cached
      # Excluir node_modules
      - /app/node_modules
    depends_on:
      - nats
      - ms-users
    networks:
      - nexus-network
    command: ["pnpm", "run", "start:dev"]
    restart: unless-stopped

  # Microservicio de Usuarios
  ms-users:
    build:
      context: ./ms-nexus-user
      dockerfile: Dockerfile.dev
      target: development
    environment:
      - NODE_ENV=development
      - NATS_SERVERS=nats://nats:4222
      - PORT=3001
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/nexus_users?authSource=admin
    volumes:
      # Montar c贸digo fuente para hot reload
      - ./ms-nexus-user/src:/app/src:cached
      - ./ms-nexus-user/package.json:/app/package.json:cached
      - ./ms-nexus-user/tsconfig.json:/app/tsconfig.json:cached
      - ./ms-nexus-user/nest-cli.json:/app/nest-cli.json:cached
      # Excluir node_modules para evitar conflictos
      - /app/node_modules
    depends_on:
      - nats
      - mongodb
    networks:
      - nexus-network
    command: ["pnpm", "run", "start:dev"]
    restart: unless-stopped

  # Microservicio de Integraci贸n
  ms-integration:
    build:
      context: ./ms-nexus-integration
      dockerfile: Dockerfile.dev
      target: development
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats:4222
      # AWS Configuration
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      # Email Configuration
      - AWS_SES_SMTP_USERNAME=${AWS_SES_SMTP_USERNAME}
      - AWS_SES_SMTP_PASSWORD=${AWS_SES_SMTP_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      # API Tokens
      - PA_TOKEN_PERUAPIS=${PA_TOKEN_PERUAPIS}
    volumes:
      # Montar c贸digo fuente para hot reload
      - ./ms-nexus-integration/src:/app/src:cached
      - ./ms-nexus-integration/package.json:/app/package.json:cached
      - ./ms-nexus-integration/tsconfig.json:/app/tsconfig.json:cached
      - ./ms-nexus-integration/nest-cli.json:/app/nest-cli.json:cached
      # Excluir node_modules para evitar conflictos
      - /app/node_modules
    depends_on:
      - nats
    networks:
      - nexus-network
    command: ["pnpm", "run", "start:dev"]
    restart: unless-stopped

volumes:
  nats_data:
    driver: local
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  nexus-network:
    driver: bridge
    name: nexus-microservices
